//! Protocol-compliance test for the in-TUI MCP HTTP server. Spins up:
//!
//!   * a `wiremock::MockServer` standing in for the control-plane
//!   * a real `tui_client::mcp::McpRuntime` pointed at that mock
//!
//! and drives JSON-RPC over real TCP against the runtime's loopback
//! endpoint, the same way Claude CLI / Codex CLI do in production. The
//! goal is to catch protocol regressions (initialize → Mcp-Session-Id
//! handshake, tools/list shape, tool-call forwarding to control-plane,
//! auth gating, origin gating) without needing a real control-plane
//! binary OR a real AI client.
//!
//! Single-test design: the runtime writes its session file to
//! `$HOME/.canopy/mcp-session.json`, which is process-global state. We
//! override `HOME` to a tempdir at the start of the test. Cargo's
//! default per-binary test parallelism means this binary's HOME
//! mutation is isolated from other test crates.

use serde_json::{json, Value};
use shared::dto::entitlements::{FeatureFlags, UserEntitlements};
use std::time::Duration;
use tui_client::api_client::ApiClient;
use tui_client::mcp::McpRuntime;
use wiremock::matchers::{body_partial_json, header, method, path};
use wiremock::{Mock, MockServer, ResponseTemplate};

/// Build a `UserEntitlements` snapshot matching what the control-plane
/// would return for `dev-admin` in dev_defaults — with MCP + database
/// MCP enabled. Sufficient for the runtime to bind its listener.
fn dev_admin_entitlements() -> UserEntitlements {
    UserEntitlements {
        user_id: "dev-admin".into(),
        email: "dev-admin@dev.local".into(),
        display_name: "dev-admin".into(),
        groups: vec!["platform-engineering".into()],
        features: FeatureFlags {
            can_view_ec2: true,
            can_use_cloudwatch_search: true,
            can_use_cloudwatch_tail: false,
            can_use_ssm: false,
            can_use_ec2_instance_connect: false,
            can_start_ec2: false,
            can_stop_ec2: false,
            can_reboot_ec2: false,
            can_use_mcp: true,
            can_use_mcp_cloudwatch: true,
            can_use_mcp_database: true,
            ..Default::default()
        },
        allowed_accounts: vec![],
        allowed_regions: vec![],
        allowed_log_group_arns: vec![],
        instance_tag_selectors: vec![],
        excluded_tag_selectors: vec![],
        allowed_clusters: vec![],
        task_tag_selectors: vec![],
        excluded_task_tag_selectors: vec![],
        excluded_container_names: vec![],
        allow_broad_cluster_discovery: false,
        allowed_os_users: vec![],
        max_session_seconds: None,
        database_scopes: vec![],
        business_scopes: vec![],
    }
}

/// Restore a previous HOME on drop so the test does not poison other
/// test binaries that might share this process (cargo test isolates per
/// binary but the safety net is cheap).
struct HomeGuard {
    previous: Option<std::ffi::OsString>,
}

impl HomeGuard {
    fn set(new_home: &std::path::Path) -> Self {
        let previous = std::env::var_os("HOME");
        std::env::set_var("HOME", new_home);
        Self { previous }
    }
}

impl Drop for HomeGuard {
    fn drop(&mut self) {
        match self.previous.take() {
            Some(prev) => std::env::set_var("HOME", prev),
            None => std::env::remove_var("HOME"),
        }
    }
}

#[tokio::test]
async fn tui_mcp_server_protocol_compliance_end_to_end() {
    // ── Phase 1: bring up the mock control-plane ────────────────────────
    let mock = MockServer::start().await;
    let expected_sid = "mcp_test_session_id_0123456789abcdef";

    // Session register → strict body matcher.
    //
    // Codex round 21 (MED): the register payload is the *only* place
    // the TUI MCP runtime announces (protocol_version, client_name,
    // product_phase, local_secret_generation) to the control plane.
    // The lsg value is dynamic (generated by the runtime), so we match
    // the three static fields with `body_partial_json` and re-check the
    // entire payload (including a non-empty `local_secret_generation`)
    // via `received_requests()` in phase 4 once the runtime is up.
    Mock::given(method("POST"))
        .and(path("/api/mcp/session/register"))
        .and(header("Authorization", "Bearer fake-jwt-for-tui-test"))
        .and(body_partial_json(json!({
            "protocol_version": "2025-06-18",
            "client_name": "canopy-local-mcp",
            "product_phase": "phase_3_data_tools"
        })))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "canopy_mcp_session_id": expected_sid,
            "forwarding_key": "fk-test-0123456789abcdefghijklmnopqrstuvwxyz",
            "expires_at": "2099-01-01T00:00:00Z"
        })))
        .mount(&mock)
        .await;

    // ── Phase 2: build ApiClient + entitlements + runtime ──────────────
    //
    // We mount the upstream-forwarding mocks (guidance/scopes/query)
    // *after* `McpRuntime::start` returns because we need the
    // runtime-generated `local_secret_generation` value to plumb into
    // their `body_partial_json` matchers. Without that, the matchers
    // would only assert that sid/scope/sql appear — the same hole
    // round 21 flagged.
    let api = ApiClient::new(&mock.uri()).expect("ApiClient::new");
    api.set_token("fake-jwt-for-tui-test".into());

    // Redirect ~/.canopy to a tempdir so the test cannot poison the
    // developer's real session file.
    let tmp_home = tempfile::tempdir().expect("home tempdir");
    let _home_guard = HomeGuard::set(tmp_home.path());

    let runtime = McpRuntime::start(api, dev_admin_entitlements())
        .await
        .expect("McpRuntime::start");
    let expected_lsg = runtime.local_secret_generation().to_string();
    assert!(
        expected_lsg.starts_with("lsg_"),
        "runtime local_secret_generation should look like 'lsg_<uuid>': {expected_lsg}"
    );

    // Codex round 20+21 (MED): every upstream mock requires the bearer
    // header AND a JSON body containing the session id, the
    // runtime-generated local_secret_generation, plus the request-
    // specific fields (scope, sql, guidance_id, ...). With these
    // strict matchers, a regression that drops the bearer, omits any
    // of these fields, or sends a stale lsg would fail the test
    // instead of silently passing. `body_partial_json` ignores fields
    // the runtime adds for its own bookkeeping while still asserting
    // the load-bearing ones.
    //
    // Guidance sync — assert (sid, lsg, guidance_id, guidance_version)
    // make it through. `.expect(1)` makes a missing `canopy_get_guidance`
    // tool call fail the test instead of leaving the mock unused.
    Mock::given(method("POST"))
        .and(path("/api/mcp/guidance/delivered"))
        .and(header("Authorization", "Bearer fake-jwt-for-tui-test"))
        .and(body_partial_json(json!({
            "canopy_mcp_session_id": expected_sid,
            "local_secret_generation": expected_lsg,
            "guidance_id": "database_query_workflow",
            "guidance_version": "2026-05-13"
        })))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "guidance_issued": true,
            "guidance_delivered_for_gating": true,
            "guidance_id": "database_query_workflow",
            "guidance_version": "2026-05-13",
            "title": "Database Query Workflow",
            "content_type": "text/markdown",
            "content": "Before issuing database queries: ..."
        })))
        .expect(1)
        .mount(&mock)
        .await;

    // List database scopes — assert (sid, lsg) make it through.
    Mock::given(method("POST"))
        .and(path("/api/mcp/database/scopes"))
        .and(header("Authorization", "Bearer fake-jwt-for-tui-test"))
        .and(body_partial_json(json!({
            "canopy_mcp_session_id": expected_sid,
            "local_secret_generation": expected_lsg
        })))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "scopes": [{
                "name": "orders_prod_readonly",
                "connection": "orders_prod",
                "environment": "production",
                "allowed_schemas": ["orders"],
                "allowed_tables": ["orders", "order_items"],
                "allowed_actions": ["select"],
                "max_rows": 100,
                "statement_timeout_ms": 5000,
                "require_explain": true,
                "max_examined_rows": 10000,
                "allow_full_table_scan": false
            }]
        })))
        .mount(&mock)
        .await;

    // List allowed log groups — assert (sid, lsg, account, region) make it through.
    Mock::given(method("POST"))
        .and(path("/api/mcp/cloudwatch/log-groups"))
        .and(header("Authorization", "Bearer fake-jwt-for-tui-test"))
        .and(body_partial_json(json!({
            "canopy_mcp_session_id": expected_sid,
            "local_secret_generation": expected_lsg,
            "account_id": "111111111111",
            "region": "us-east-1",
            "prefix": "/app"
        })))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "account_id": "111111111111",
            "region": "us-east-1",
            "prefix": "/app",
            "log_groups": [{
                "name": "/app/web-service",
                "arn": "arn:aws:logs:us-east-1:111111111111:log-group:/app/web-service",
                "stored_bytes": 1024,
                "retention_days": 30
            }],
            "returned_count": 1,
            "scanned_count": 1,
            "truncated": false
        })))
        .mount(&mock)
        .await;

    // CloudWatch preflight — assert Phase 3 data tools carry sid/lsg and scoped intent.
    Mock::given(method("POST"))
        .and(path("/api/mcp/cloudwatch/preflight"))
        .and(header("Authorization", "Bearer fake-jwt-for-tui-test"))
        .and(body_partial_json(json!({
            "canopy_mcp_session_id": expected_sid,
            "local_secret_generation": expected_lsg,
            "tool_name": "canopy_search_logs",
            "account_id": "111111111111",
            "region": "us-east-1",
            "log_group_name": "/app/web-service",
            "filter_pattern": "ERROR",
            "start_time": 1000,
            "end_time": 2000,
            "limit": 2
        })))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "tool_name": "canopy_search_logs",
            "account_id": "111111111111",
            "region": "us-east-1",
            "log_group_names": ["/app/web-service"],
            "preflight_token": "pf-token-1",
            "expires_at": "2099-01-01T00:00:00Z",
            "guardrails": {
                "max_request_body_bytes": 262144,
                "max_log_group_list_results": 200,
                "max_describe_log_groups_pages": 5,
                "max_discovery_results_scanned": 1000,
                "discovery_cursor_ttl_seconds": 600,
                "preflight_token_ttl_seconds": 300,
                "search_cursor_ttl_seconds": 600,
                "insights_query_token_ttl_seconds": 900,
                "max_search_window_seconds": 21600,
                "max_search_events": 1000,
                "max_response_bytes": 1048576,
                "max_event_message_bytes": 16384,
                "max_insights_timeout_seconds": 60,
                "default_insights_timeout_seconds": 30,
                "max_concurrent_mcp_tool_calls_per_session": 4,
                "max_concurrent_insights_queries_per_actor": 2,
                "max_mcp_tool_calls_per_actor_per_minute": 30,
                "max_insights_starts_per_actor_per_minute": 10
            }
        })))
        .expect(1)
        .mount(&mock)
        .await;

    // CloudWatch search — assert only the preflight token is forwarded for initial mode.
    Mock::given(method("POST"))
        .and(path("/api/mcp/cloudwatch/search"))
        .and(header("Authorization", "Bearer fake-jwt-for-tui-test"))
        .and(body_partial_json(json!({
            "canopy_mcp_session_id": expected_sid,
            "local_secret_generation": expected_lsg,
            "preflight_token": "pf-token-1"
        })))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "account_id": "111111111111",
            "region": "us-east-1",
            "log_group_name": "/app/web-service",
            "events": [{
                "timestamp": 1000,
                "message": "{\"level\":\"ERROR\",\"msg\":\"Connection refused\"}",
                "log_stream_name": "worker-prod-01/application",
                "ingestion_time": 1100,
                "event_id": "ev-test-1"
            }],
            "returned_count": 1,
            "truncated": false
        })))
        .expect(1)
        .mount(&mock)
        .await;

    // CloudWatch Insights — assert the query starter forwards its preflight token.
    Mock::given(method("POST"))
        .and(path("/api/mcp/cloudwatch/insights"))
        .and(header("Authorization", "Bearer fake-jwt-for-tui-test"))
        .and(body_partial_json(json!({
            "canopy_mcp_session_id": expected_sid,
            "local_secret_generation": expected_lsg,
            "preflight_token": "pf-token-1"
        })))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "account_id": "111111111111",
            "region": "us-east-1",
            "log_group_names": ["/app/web-service"],
            "query_token": "query-token-1",
            "status": "Running",
            "results": [],
            "terminal": false,
            "next_action_hint": "Use query_token to poll this exact Insights query."
        })))
        .expect(1)
        .mount(&mock)
        .await;

    // Query database — assert (sid, lsg, scope, sql) make it through.
    Mock::given(method("POST"))
        .and(path("/api/mcp/database/query"))
        .and(header("Authorization", "Bearer fake-jwt-for-tui-test"))
        .and(body_partial_json(json!({
            "canopy_mcp_session_id": expected_sid,
            "local_secret_generation": expected_lsg,
            "scope": "orders_prod_readonly",
            "sql": "select id from orders limit 1"
        })))
        .respond_with(ResponseTemplate::new(400).set_body_json(json!({
            "code": "BAD_REQUEST",
            "message": "Database connection is not configured"
        })))
        .mount(&mock)
        .await;

    let status = runtime.status();
    let endpoint = status.endpoint.clone(); // direct (dynamic) port
    let session_file = tmp_home.path().join(".canopy/mcp-session.json");
    assert!(
        session_file.exists(),
        "session file should be written: {}",
        session_file.display()
    );
    let session: Value =
        serde_json::from_str(&std::fs::read_to_string(&session_file).unwrap()).unwrap();
    let bearer = session["bearer_token"]
        .as_str()
        .expect("bearer_token in session file")
        .to_string();
    assert_eq!(
        session["session_file_version"], 1,
        "session file version pinned"
    );

    // ── Phase 3: drive the runtime over real TCP ────────────────────────
    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(5))
        .build()
        .unwrap();
    let healthz = endpoint.replace("/mcp", "/healthz");

    // 3.1 /healthz without bearer → 401
    let resp = client.get(&healthz).send().await.expect("healthz unauth");
    assert_eq!(
        resp.status().as_u16(),
        401,
        "/healthz must require bearer auth"
    );

    // 3.2 /healthz with wrong bearer → 401 (constant-time compare)
    let resp = client
        .get(&healthz)
        .bearer_auth("wrong-token-same-length-as-real-one-padding-pad")
        .send()
        .await
        .unwrap();
    assert_eq!(resp.status().as_u16(), 401, "wrong bearer must be rejected");

    // 3.3 /healthz with right bearer → 200 + protocol fields
    let resp = client
        .get(&healthz)
        .bearer_auth(&bearer)
        .send()
        .await
        .unwrap();
    assert_eq!(resp.status().as_u16(), 200);
    let body: Value = resp.json().await.unwrap();
    assert_eq!(body["ok"], true);
    assert_eq!(body["protocol_version"], "2025-06-18");
    assert_eq!(body["server"], "canopy-local-mcp");

    // 3.4 Origin: non-null and non-empty → reject (browser CSRF guard)
    let resp = client
        .post(&endpoint)
        .bearer_auth(&bearer)
        .header("Origin", "https://evil.example.com")
        .header("Content-Type", "application/json")
        .body(r#"{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2025-06-18","capabilities":{},"clientInfo":{"name":"t","version":"0"}}}"#)
        .send()
        .await
        .unwrap();
    assert!(
        resp.status().is_client_error(),
        "non-null Origin must be rejected, got {:?}",
        resp.status()
    );

    // 3.5 MCP initialize → 200 + Mcp-Session-Id header
    let resp = client
        .post(&endpoint)
        .bearer_auth(&bearer)
        .header("Content-Type", "application/json")
        .json(&json!({
            "jsonrpc": "2.0",
            "id": 1,
            "method": "initialize",
            "params": {
                "protocolVersion": "2025-06-18",
                "capabilities": {},
                "clientInfo": {"name": "p3-test", "version": "0.0.1"}
            }
        }))
        .send()
        .await
        .unwrap();
    assert_eq!(resp.status().as_u16(), 200);
    let proto_session_id = resp
        .headers()
        .get("mcp-session-id")
        .expect("Mcp-Session-Id on initialize response")
        .to_str()
        .unwrap()
        .to_string();
    assert!(
        proto_session_id.starts_with("mcp-proto-"),
        "proto session id has expected prefix: {proto_session_id}"
    );
    let body: Value = resp.json().await.unwrap();
    assert_eq!(body["result"]["protocolVersion"], "2025-06-18");
    assert_eq!(body["result"]["serverInfo"]["name"], "canopy-local-mcp");

    // 3.6 tools/list without Mcp-Session-Id → reject
    let resp = client
        .post(&endpoint)
        .bearer_auth(&bearer)
        .header("Content-Type", "application/json")
        .json(&json!({"jsonrpc": "2.0", "id": 2, "method": "tools/list", "params": {}}))
        .send()
        .await
        .unwrap();
    assert!(
        !resp.status().is_success() || resp.text().await.unwrap().contains("Mcp-Session-Id"),
        "tools/list without protocol session id must fail"
    );

    // 3.7 tools/list with session id → expected tools
    let resp = client
        .post(&endpoint)
        .bearer_auth(&bearer)
        .header("Content-Type", "application/json")
        .header("Mcp-Session-Id", &proto_session_id)
        .json(&json!({"jsonrpc": "2.0", "id": 3, "method": "tools/list", "params": {}}))
        .send()
        .await
        .unwrap();
    assert_eq!(resp.status().as_u16(), 200);
    let body: Value = resp.json().await.unwrap();
    let tools = body["result"]["tools"]
        .as_array()
        .expect("tools array in response");
    let names: Vec<&str> = tools.iter().map(|t| t["name"].as_str().unwrap()).collect();
    for expected in [
        "canopy_describe_capabilities",
        "canopy_get_guidance",
        "canopy_list_allowed_log_groups",
        "canopy_preflight_request",
        "canopy_search_logs",
        "canopy_run_insights_query",
        "canopy_list_database_scopes",
        "canopy_query_database",
    ] {
        assert!(
            names.contains(&expected),
            "tools/list must include {expected}; got {names:?}"
        );
    }

    // 3.8 tools/call canopy_describe_capabilities → 200, no upstream call
    let resp = client
        .post(&endpoint)
        .bearer_auth(&bearer)
        .header("Content-Type", "application/json")
        .header("Mcp-Session-Id", &proto_session_id)
        .json(&json!({
            "jsonrpc": "2.0", "id": 4, "method": "tools/call",
            "params": {"name": "canopy_describe_capabilities", "arguments": {}}
        }))
        .send()
        .await
        .unwrap();
    assert_eq!(resp.status().as_u16(), 200);
    let body: Value = resp.json().await.unwrap();
    let payload_text = body["result"]["content"][0]["text"]
        .as_str()
        .expect("content[0].text");
    let payload: Value = serde_json::from_str(payload_text).unwrap();
    assert_eq!(payload["mcp_product_phase"], "phase_3_data_tools");

    // 3.9 tools/call canopy_get_guidance → forwards to control-plane
    //     `/api/mcp/guidance/delivered` with the workflow guidance id.
    //
    // Codex round 21 (MED): the guidance/delivered mock previously
    // had `.expect(1)` set but no MCP tool actually triggered it,
    // which means the mock could be entirely unused and the test
    // would still go green. Drive a real `canopy_get_guidance` call
    // so the mock's matcher (sid + lsg + guidance_id + version) is
    // exercised end-to-end.
    let resp = client
        .post(&endpoint)
        .bearer_auth(&bearer)
        .header("Content-Type", "application/json")
        .header("Mcp-Session-Id", &proto_session_id)
        .json(&json!({
            "jsonrpc": "2.0", "id": 5, "method": "tools/call",
            "params": {
                "name": "canopy_get_guidance",
                "arguments": {"guidance_id": "database_query_workflow"}
            }
        }))
        .send()
        .await
        .unwrap();
    assert_eq!(resp.status().as_u16(), 200);
    let body: Value = resp.json().await.unwrap();
    let payload_text = body["result"]["content"][0]["text"]
        .as_str()
        .expect("content[0].text on get_guidance");
    let payload: Value = serde_json::from_str(payload_text).unwrap();
    assert_eq!(payload["id"], "database_query_workflow");
    assert_eq!(payload["version"], "2026-05-13");

    // 3.10 tools/call canopy_list_allowed_log_groups → forwards to mock
    //      control-plane; it is discovery and does not require
    //      a preflight token.
    let resp = client
        .post(&endpoint)
        .bearer_auth(&bearer)
        .header("Content-Type", "application/json")
        .header("Mcp-Session-Id", &proto_session_id)
        .json(&json!({
            "jsonrpc": "2.0", "id": 6, "method": "tools/call",
            "params": {
                "name": "canopy_list_allowed_log_groups",
                "arguments": {
                    "account_id": "111111111111",
                    "region": "us-east-1",
                    "prefix": "/app"
                }
            }
        }))
        .send()
        .await
        .unwrap();
    assert_eq!(resp.status().as_u16(), 200);
    let body: Value = resp.json().await.unwrap();
    let payload_text = body["result"]["content"][0]["text"]
        .as_str()
        .expect("content[0].text on list_allowed_log_groups");
    let payload: Value = serde_json::from_str(payload_text).unwrap();
    assert_eq!(payload["log_groups"][0]["name"], "/app/web-service");
    assert_eq!(payload["truncated"], false);

    // 3.11 tools/call canopy_preflight_request → forwards scoped CloudWatch data intent.
    let resp = client
        .post(&endpoint)
        .bearer_auth(&bearer)
        .header("Content-Type", "application/json")
        .header("Mcp-Session-Id", &proto_session_id)
        .json(&json!({
            "jsonrpc": "2.0", "id": 7, "method": "tools/call",
            "params": {
                "name": "canopy_preflight_request",
                "arguments": {
                    "tool_name": "canopy_search_logs",
                    "account_id": "111111111111",
                    "region": "us-east-1",
                    "log_group_name": "/app/web-service",
                    "filter_pattern": "ERROR",
                    "start_time": 1000,
                    "end_time": 2000,
                    "limit": 2
                }
            }
        }))
        .send()
        .await
        .unwrap();
    assert_eq!(resp.status().as_u16(), 200);
    let body: Value = resp.json().await.unwrap();
    let payload_text = body["result"]["content"][0]["text"]
        .as_str()
        .expect("content[0].text on cloudwatch preflight");
    let payload: Value = serde_json::from_str(payload_text).unwrap();
    assert_eq!(payload["preflight_token"], "pf-token-1");

    // 3.12 tools/call canopy_search_logs → forwards preflight token.
    let resp = client
        .post(&endpoint)
        .bearer_auth(&bearer)
        .header("Content-Type", "application/json")
        .header("Mcp-Session-Id", &proto_session_id)
        .json(&json!({
            "jsonrpc": "2.0", "id": 8, "method": "tools/call",
            "params": {
                "name": "canopy_search_logs",
                "arguments": {"preflight_token": "pf-token-1"}
            }
        }))
        .send()
        .await
        .unwrap();
    assert_eq!(resp.status().as_u16(), 200);
    let body: Value = resp.json().await.unwrap();
    let payload_text = body["result"]["content"][0]["text"]
        .as_str()
        .expect("content[0].text on cloudwatch search");
    let payload: Value = serde_json::from_str(payload_text).unwrap();
    assert_eq!(payload["events"][0]["event_id"], "ev-test-1");
    assert_eq!(payload["truncated"], false);

    // 3.13 tools/call canopy_run_insights_query → forwards preflight token.
    let resp = client
        .post(&endpoint)
        .bearer_auth(&bearer)
        .header("Content-Type", "application/json")
        .header("Mcp-Session-Id", &proto_session_id)
        .json(&json!({
            "jsonrpc": "2.0", "id": 9, "method": "tools/call",
            "params": {
                "name": "canopy_run_insights_query",
                "arguments": {"preflight_token": "pf-token-1"}
            }
        }))
        .send()
        .await
        .unwrap();
    assert_eq!(resp.status().as_u16(), 200);
    let body: Value = resp.json().await.unwrap();
    let payload_text = body["result"]["content"][0]["text"]
        .as_str()
        .expect("content[0].text on cloudwatch insights");
    let payload: Value = serde_json::from_str(payload_text).unwrap();
    assert_eq!(payload["query_token"], "query-token-1");
    assert_eq!(payload["status"], "Running");

    // 3.14 tools/call canopy_list_database_scopes → forwards to mock
    //     control-plane; we verify the response shape AND that the mock
    //     actually saw the request below.
    let resp = client
        .post(&endpoint)
        .bearer_auth(&bearer)
        .header("Content-Type", "application/json")
        .header("Mcp-Session-Id", &proto_session_id)
        .json(&json!({
            "jsonrpc": "2.0", "id": 10, "method": "tools/call",
            "params": {"name": "canopy_list_database_scopes", "arguments": {}}
        }))
        .send()
        .await
        .unwrap();
    assert_eq!(resp.status().as_u16(), 200);
    let body: Value = resp.json().await.unwrap();
    let payload_text = body["result"]["content"][0]["text"]
        .as_str()
        .expect("content[0].text on list_scopes");
    let payload: Value = serde_json::from_str(payload_text).unwrap();
    assert_eq!(payload["scopes"][0]["name"], "orders_prod_readonly");

    // 3.15 tools/call canopy_query_database → control-plane returns 400
    //      which the TUI MCP server should surface as a structured
    //      JSON-RPC error, not a 5xx.
    let resp = client
        .post(&endpoint)
        .bearer_auth(&bearer)
        .header("Content-Type", "application/json")
        .header("Mcp-Session-Id", &proto_session_id)
        .json(&json!({
            "jsonrpc": "2.0", "id": 11, "method": "tools/call",
            "params": {
                "name": "canopy_query_database",
                "arguments": {
                    "scope": "orders_prod_readonly",
                    "sql": "select id from orders limit 1"
                }
            }
        }))
        .send()
        .await
        .unwrap();
    assert_eq!(resp.status().as_u16(), 200, "JSON-RPC errors return 200");
    let body: Value = resp.json().await.unwrap();
    let error_message = body["error"]["message"]
        .as_str()
        .expect("error.message on forwarded upstream rejection");
    assert!(
        error_message.contains("Database connection is not configured"),
        "expected upstream error to be relayed, got {error_message:?}"
    );

    // ── Phase 4: assert mock control-plane saw the expected forwards ───
    let received = mock.received_requests().await.unwrap_or_default();
    let path_counts: std::collections::HashMap<&str, usize> = [
        "/api/mcp/session/register",
        "/api/mcp/guidance/delivered",
        "/api/mcp/cloudwatch/log-groups",
        "/api/mcp/cloudwatch/preflight",
        "/api/mcp/cloudwatch/search",
        "/api/mcp/cloudwatch/insights",
        "/api/mcp/database/scopes",
        "/api/mcp/database/query",
    ]
    .iter()
    .map(|p| {
        let n = received.iter().filter(|r| r.url.path() == *p).count();
        (*p, n)
    })
    .collect();
    assert_eq!(
        path_counts["/api/mcp/session/register"], 1,
        "runtime should register session exactly once"
    );
    // Codex round 21 (MED): explicitly assert guidance/delivered was
    // hit by the `canopy_get_guidance` tool call. The mock has
    // `.expect(1)` so this is a belt-and-suspenders check — but it
    // also documents the contract for future readers.
    assert_eq!(
        path_counts["/api/mcp/guidance/delivered"], 1,
        "canopy_get_guidance must forward to control-plane exactly once"
    );
    assert!(
        path_counts["/api/mcp/cloudwatch/log-groups"] >= 1,
        "list_allowed_log_groups tool must forward to control-plane"
    );
    assert_eq!(
        path_counts["/api/mcp/cloudwatch/preflight"], 1,
        "preflight tool must forward to control-plane exactly once"
    );
    assert_eq!(
        path_counts["/api/mcp/cloudwatch/search"], 1,
        "search tool must forward to control-plane exactly once"
    );
    assert_eq!(
        path_counts["/api/mcp/cloudwatch/insights"], 1,
        "insights tool must forward to control-plane exactly once"
    );
    assert!(
        path_counts["/api/mcp/database/scopes"] >= 1,
        "list_scopes tool must forward to control-plane"
    );
    assert_eq!(
        path_counts["/api/mcp/database/query"], 1,
        "query tool must forward to control-plane exactly once"
    );

    // Codex round 21 (MED): re-decode the register payload from the
    // recorded request and assert the full contract — protocol /
    // client name / product phase via the body matcher above, plus the
    // dynamic `local_secret_generation` field that has to be a
    // non-empty `lsg_*` string matching what the runtime advertises.
    // Without this, a regression that registers with an empty or
    // stale lsg would still match the partial JSON matcher.
    let register_req = received
        .iter()
        .find(|r| r.url.path() == "/api/mcp/session/register")
        .expect("register request captured");
    let register_body: Value =
        serde_json::from_slice(&register_req.body).expect("register body should be JSON");
    assert_eq!(register_body["protocol_version"], "2025-06-18");
    assert_eq!(register_body["client_name"], "canopy-local-mcp");
    assert_eq!(register_body["product_phase"], "phase_3_data_tools");
    assert_eq!(
        register_body["local_secret_generation"], expected_lsg,
        "register must carry the runtime-generated local_secret_generation"
    );

    // ── Phase 5: shutdown ──────────────────────────────────────────────
    runtime.stop().expect("McpRuntime::stop");
    // session file cleaned up on stop
    assert!(
        !session_file.exists(),
        "session file should be removed on stop: {}",
        session_file.display()
    );
    // After stop, the listener should refuse new connections quickly.
    tokio::time::sleep(Duration::from_millis(50)).await;
    let probe = client
        .get(&healthz)
        .bearer_auth(&bearer)
        .timeout(Duration::from_millis(500))
        .send()
        .await;
    assert!(
        probe.is_err() || !probe.unwrap().status().is_success(),
        "post-stop request must fail to connect or get non-success"
    );
}
